Table TableA [note: 'This is table A'] {
  Id             varchar(10)   [primary key, not null]
  BId            varchar(10)   [ref: > TableB.Id]
  Name           "super string"  [unique, note: 'Name']
  IntValue       integer       [null, note: 'Integer Value']
  DecimalValue   decimal(10,2) [default: 10.24]
  DateValue      date
  DateTimeValue  datetime
}

TablePartial TableB {
  Id             varchar(10)   [primary key, not null]
}

TablePartial TableC {
  IntValue        integer   [ref: - TableA.IntValue]
}

Table "schema1"."Table D" as D {
  ~TableB
  Name           "super string"  [unique, note: 'Name']
  ~TableC

  Note: 'Includes TableB & TableC'
}
