# .github/workflows/release.yml

name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-test-and-publish:
    name: Build, Test, and Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lark-dbml
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv (including dev for tests)
        run: uv sync --dev

      - name: Run unit tests and collect coverage
        run: |
          uv run pytest --cov=lark_dbml --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml

      - name: Build sdist and wheel
        run: uv build

      - name: Check dist/ contents (for debugging)
        run: ls -l dist/

      - name: Verify dist files with twine check
        run: uv run twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
